### ISSUE TITLE
hapi v17 support

### ISSUE THREAD

**Issue by hueniverse** [hapijs/good#568] opened 2017-11-04 00:20 UTC
What's the plan? Migrate? Deprecate?

**Comment by arb** [comment] 2017-11-04 16:17
Migration shouldn't be difficult but I really don't have the time to change the reporting interface again. I didn't get a strong opinion either way in the slack about deprecating good or not. The npm downloads, which I realize aren't a perfect metric, is in the thousands per day so people must be using it.

**Comment by corbinu** [comment] 2017-11-04 18:12
I am using it but would be open to transition what would the plan be to migrate to? Winston or something else?

**Comment by BorntraegerMarc** [comment] 2017-11-06 09:12
@arb is there an ETA when we could expect an update? Now that hapi v17 final has been released 😄

**Comment by AdriVanHoudt** [comment] 2017-11-08 09:22
If you want v17 support for this the best way is to submit a PR ;)

**Comment by PizzaBrandon** [comment] 2017-11-08 23:12
I like `good` and want it to survive. I'll take a crack at this and see what I can do, but I also encourage others to take up the cause, too.

If `good` is deprecated, what (if anything) is its replacement?

**Comment by g-corneu** [comment] 2017-11-09 10:02
I quite like and am currently using `good`. I'll have a stab at migrating and opening a PR. :smile:

**Comment by corbinu** [comment] 2017-11-15 21:13
@g-corneu Any luck? Otherwise I will take a stab also

**Comment by g-corneu** [comment] 2017-11-15 22:20
@corbinu I'm finishing up porting [oppsy](https://github.com/hapijs/oppsy) and am hoping to open a PR for that in the next couple of days since good depends on it. I'll move on to porting good after that; should be able to spend some dedicated time on it this weekend + first 2 days of next week. Happy to work together if you're interested and free.

**Comment by corbinu** [comment] 2017-11-27 14:19
@g-corneu I finally had some time now that it is after Black Friday. I have a version of oppsy that is ready to go and have made some progress on good. Would be happy to sync up if you like.

**Comment by g-corneu** [comment] 2017-11-27 17:42
> @g-corneu I finally had some time now that it is after Black Friday. I have
> a version of oppsy that is ready to go and have made some progress on good.
> Would be happy to sync up if you like.

I've had a lot less free time than I thought I would. :(

Feel free to do the PRs, if there's anything I can help with give me a shout.
:)

-- 
Geraint Corneu
Full Stack Developer @ [Appointedd](https://www.appointedd.com/)

For my public PGP key or secure communications you can find me on
[Keybase](https://keybase.io/geraintcorneu/).

For other ways of contacting me visit my
[landing page](https://geraintcorneu.gitlab.io/landing-page/).

**Comment by corbinu** [comment] 2017-11-27 22:09
No worries TOTALLY know that feeling good luck!

Will do thanks mostly now just doing more upgrades to node 8 syntax rather than just getting them working.

**Comment by lostthetrail** [comment] 2017-12-01 13:32
@arb @hueniverse My understanding was that Good was the standard logging plugin for Hapi.js. What are y'all using that makes Good a potential target for deprecation?

**Comment by hueniverse** [comment] 2017-12-01 18:49
@lostthetrail people use a bunch of different solutions. I use my own.

**Comment by framerate** [comment] 2017-12-07 02:36
> @lostthetrail people use a bunch of different solutions. I use my own.

Do you have any examples? I've been using good for a few years now and would love to investigate some v17 compatible alternatives!

**Comment by corbinu** [comment] 2017-12-07 02:40
Just an update I am digging through the last few issues and waiting for release of my oppsy update. Hoping to have a PR up in the next few days. Work just keeps getting in my way.

**Comment by corbinu** [comment] 2017-12-07 05:44
Pushed up my progress here: https://github.com/corbinu/good

Turned out some of the errors are just that goods current test suite fails on OS X. It is green on Linux now.

However I am getting an warning from node: "Possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit"

It does drop support for Wreck logging as the global events were removed in the most recent versions of Wreck. 

Feel free to try it out and give feedback!

**Comment by framerate** [comment] 2017-12-07 18:44
@corbinu I set it up in its most basic form and I have route logging printing now, so far so good!

**Comment by fhemberger** [comment] 2017-12-14 10:05
@framerate For simple logging I switched to bunyan (using [hapi-bunny](https://github.com/m1ome/hapi-bunny)). As I mostly run containerized Node.js applications these days, I only need to log to `stdout`/`stderr`. Ops related stats are handled by Docker or Prometheus (https://github.com/siimon/prom-client).

**Comment by arb** [comment] 2017-12-21 14:42
Closed via #572

**Closed by arb** 2017-12-21 14:42 UTC
Labels: breaking changes, dependency, discussion, help wanted
