### ISSUE TITLE
Please add support for joi@6.x

### ISSUE THREAD

**Issue by lancespeelmon** [hapijs/good#349] opened 2015-05-27 18:13 UTC
hello I am trying to upgrade joi from 5.1.0 to 6.x and get this warning:
`npm WARN unmet dependency /Develop/trax/document-service/node_modules/good requires joi@'5.x.x' but will load`
but when I hit: 
```
server.register({
   register: require('good'),
```
I get: 
```
TypeError: undefined is not a function`
   at Object.<anonymous> (/Develop/trax/document-service/node_modules/good/lib/schema.js:21:28)
```
Is there a workaround or do you think it warrants a github issue?
[10:06am] nlf: lancespeelmon: try updating your installation of good
I think I have done that - here is where my depds are: https://gist.github.com/aa7fb43f63f1ea2d4c55
i.e.    `"good": "^6.1.3",`
Here is the line that bombs: `    reporters: Joi.array().includes(Joi.object(), Joi.string()).required().min(1),`
There are other Joi references before that line - so must be a joi 5.x/6.x compat issue

**Comment by arb** [comment] 2015-05-27 18:16
Duplicate of https://github.com/hapijs/good/issues/348

**Closed by arb** 2015-05-27 18:16 UTC

**Comment by Marsup** [comment] 2015-05-27 18:21
That's what happens when you work on modules individually, had you reinstalled all your dependencies with that same package.json you would not have had the problem. This should be addressed by npm 3 in the future.
